=== P4thos/eggofpanku/settings.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:eopk="http://code.google.com/p/eopk/"
	targetNamespace="http://code.google.com/p/eopk/">
	
	<xsd:element name="settings" type="eopk:SettingsList" />
	
	<xsd:complexType name="SettingsList">
		<xsd:sequence>
			<xsd:element name="setting" type="xsd:string" minOccurs="0" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== P4thos/eggofpanku/settings.xml
<?xml version="1.0" ?>
  <eopk:settings eopk:schemaLocation="http://code.google.com/p/eopk/ http://www.torchdragon.com/l5r/settings.xsd" xmlns:eopk="http://code.google.com/p/eopk/">
    
    <eopk:setting name="playfield_bg_image">''</eopk:setting>
    
    <eopk:setting name="attach_ok">('personality',)</eopk:setting>
    
    <eopk:setting name="legacy_card_draw">False</eopk:setting>
    
    <eopk:setting name="canvas_card_spacing">1</eopk:setting>
    
    <eopk:setting name="playfield_bg_color2">(0, 190, 16)</eopk:setting>
    
    <eopk:setting name="playfield_bg_color1">(0, 206, 24)</eopk:setting>
    
    <eopk:setting name="playfield_snap">True</eopk:setting>
    
    <eopk:setting name="playername">'Toku-san'</eopk:setting>
    
    <eopk:setting name="mainwindow_size">(780, 560)</eopk:setting>
    
    <eopk:setting name="cardsource">u'/home/gryffon/Code/Checkouts/eggofpanku/cards-emperor.xml'</eopk:setting>
    
    <eopk:setting name="matchpassword">'1234'</eopk:setting>
    
    <eopk:setting name="dir_imagepacks">'images/cards/'</eopk:setting>
    
    <eopk:setting name="matchuser">''</eopk:setting>
    
    <eopk:setting name="log_multiplayer_games">False</eopk:setting>
    
    <eopk:setting name="playfield_bg_image_display">False</eopk:setting>
    
    <eopk:setting name="maximize">False</eopk:setting>
    
    <eopk:setting name="gameport">18072</eopk:setting>
    
    <eopk:setting name="last_deck">''</eopk:setting>
    
    <eopk:setting name="playfield_bg_mode">0</eopk:setting>
    
    <eopk:setting name="gamehost">'localhost'</eopk:setting>
    
    <eopk:setting name="use_celestial_holdings">True</eopk:setting>
    
  </eopk:settings>
